IS_ontology/IS_ontology/Accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from IS_ontology.Notes.views import view_NotesList
from IS_ontology.Accounts.views import view_Register

urlpatterns = [
    path(r'login/',                auth_views.LoginView.as_view(),              name='login'),
    path(r'logout/',               auth_views.LogoutView.as_view(),             name='logout'),
    path(r'password_change/',      auth_views.PasswordChangeView.as_view(),     name='password_change'),
    path(r'password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path(r'password_change/',      auth_views.PasswordChangeView.as_view(),     name='password_change'),
    path(r'register/',             view_Register,                               name='register'),
    path('',                       view_NotesList,                              name='notes_list'),
]

IS_ontology/IS_ontology/Clf/urls.py
from django.urls import path

from . import views


app_name = 'Clf'


urlpatterns = [
    path('', views.index, name='clf'),
]

IS_ontology/IS_ontology/Ie/urls.py
from django.urls import path

from . import views


app_name = 'Ie'

urlpatterns = [
    path('', views.IndexView.as_view(), name='ie'),
    path('graph', views.graph, name='graph'),
    path('add', views.AddView.as_view(), name='add'),
    path('predicates', views.PredicateView.as_view(), name='predicates'),
    path('build_graph', views.build_graph)
]

IS_ontology/IS_ontology/Notes/urls.py
from django.urls import path, include
from .views import (
    index,
    main,
    fz,
    pp,
    fstek,
    companies,
    members,
    terms,
    triplets,
    triplet_table,
    rep_2021_jul,
    rep_2021_aug,
    terms_to_vote,
    terms_table,
    triples_to_vote,
    eng_rate,
    exp_rate,
)

app_name = "IS_ontology"

urlpatterns = [
    path("", index, name="index"),
    path("main", main, name="main"),
    path("fz", fz, name="fz"),
    path("pp", pp, name="pp"),
    path("fstek", fstek, name="fstek"),
    path("terms", terms, name="terms"),
    path("terms/table", terms_table),
    path("rep_2021_jul", rep_2021_jul, name="rep_2021_jul"),
    path("rep_2021_aug", rep_2021_aug, name="rep_2021_aug"),
    path("triplets", triplets, name="triplets"),
    path("triplets/table", triplet_table),
    path("companies", companies, name="companies"),
    path("members", members, name="members"),
    path("exp_rate", exp_rate, name="expert_rating"),
    path("eng_rate", eng_rate, name="engineer_rating"),
    path("terms_to_vote", terms_to_vote, name="terms_to_vote"),
    path("triples_to_vote", triples_to_vote, name="triples_to_vote"),
    #     path(r'<int:year>/<int:month>/<int:day>/<slug:code>', view_NoteDetails, name='note_details'),
    #     path('InputNote',                                     view_InputNote,   name='input_note'),
    #     path('NotesList',                                     view_NotesList,   name='notes_list'),
    #     path('api', NoteAPIView.as_view()),
    #     path('api/<int:year>/<int:month>/<int:day>/<slug:code>', NoteAPIView.as_view()),
    path("information_extraction", include("IS_ontology.Ie.urls")),
    path("classifier", include("IS_ontology.Clf.urls")),
]

IS_ontology/IS_ontology/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path, include
from rest_framework.schemas import get_schema_view

api_patterns = [
    path("api/", include("IS_ontology.api.urls")),
]

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("IS_ontology.Accounts.urls")),
    api_patterns[0],
    path('api_docs/', get_schema_view("IS_ontology", patterns=api_patterns)),
    path("clf/", include("IS_ontology.Clf.urls", namespace="Clf")),
    path("components/", include("components.urls")),
    path("ie/", include("IS_ontology.Ie.urls", namespace="Ie")),
    path("", include("IS_ontology.Notes.urls", namespace="Notes")),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns+= static('/static')

IS_ontology/components/urls.py
from django.urls import path, include
from . import views

app_name = "components"
urlpatterns = [
    path('filter/', views.filter_view, name='filter')
]

IS_ontology/IS_ontology/Clf/models.py
from django.db import models

# Create your models here.

IS_ontology/IS_ontology/Ie/models.py
from django.db import models

# Create your models here.

IS_ontology/IS_ontology/Clf/views.py
import os

from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render
import requests
import re
from bs4 import BeautifulSoup
import pickle
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense, Embedding, LSTM
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from django.conf import settings
import pickle

from ..Ie.graph_repositories import SourceRepository
from ..Notes.models import Source, Text


tokenizer_path = os.path.join(str(settings.BASE_DIR), "tokenizer.pickle")

model_path = os.path.join(str(settings.BASE_DIR), "clf_is.h5")
print(model_path)

# with open(tokenizer_path, "rb") as handle:
#     tokenizer = pickle.load(handle)


# classifier = Sequential()
# classifier.add(Embedding(20000, 64, input_length=400))
# classifier.add(LSTM(64))
# classifier.add(Dense(1, activation="sigmoid"))
# classifier.compile(
#     optimizer="adam", loss="binary_crossentropy", metrics=["AUC", "accuracy"]
# )

# classifier.load_weights(model_path)

last = {}


def index(request: WSGIRequest):
    context = {}
    global last

    if request.method == "GET":
        context["show_verdict"] = False
        context["show"] = False

    if request.method == "POST" and "classify" in request.POST:
        last_url = request.POST.get("request_url")
        if check_url(last_url):
            if check_text(get_parsed_html(last_url)):
                result = predict(tokenizer, classifier, last_url)
                context["request_type"] = result
                context["show"] = True
                last[request.user] = last_url
            else:
                context["request_type"] = "Не удалось спарсить текст."

    if request.method == "POST" and "add_to_base" in request.POST:
        description = request.POST.get("request_description")
        url = last[request.user]
        verdict = check_source(url, description, request.user.pk)
        context["verdict"] = verdict[0]
        context["description"] = verdict[1]
        context["show_verdict"] = True

    return render(request, "clf.html", context)


def check_url(url):
    try:
        if str(requests.get(url)) != "<Response [404]>":
            return True
        return False
    except requests.exceptions.SSLError:
        return False


def check_text(text):
    if len(text) != 0:
        return True
    return False


def check_source(url: str, description: str, user) -> tuple[str, str]:
    if Source.objects.filter(url=url):
        return (
            "Статья уже есть в базе",
            "Описание статьи: " + str(Source.objects.filter(url=url)[0].description),
        )
    else:
        source = Source(url=url, description=description)
        source.save()
        SourceRepository(url, description, source.date, user).create()
        text = Text(source=source, text=get_parsed_html(url))
        text.save()
        return (
            "Статья добавлена",
            "Описание статьи: " + Source.objects.filter(url=url)[0].description,
        )


def predict(tokenizer, model, url):
    text = get_parsed_html(url)
    sequence = tokenizer.texts_to_sequences([text])
    sequence = pad_sequences(sequence, maxlen=400)
    proba = model.predict(sequence)[0][0]
    return (
        "Cтатья относится к информационной безопасности с вероятностью "
        + str(proba)[:4]
    )


def get_parsed_html(link):
    doc = requests.get(link)
    soup = BeautifulSoup(doc.text, "html.parser")
    text = []
    for p in soup.find_all("p"):
        if len(p.text.split()) > 4:
            s = p.text
            s = s.replace("\xa0", " ")
            s = re.sub("\d\)", "", s).strip()
            text.append(s)
    return " ".join([x for x in text])

IS_ontology/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title> 
	    {% block title %}{% endblock %} 
    </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="{% static "css/main.css" %}" rel="stylesheet">
</head>
<body>

    {% block info %}{% endblock %}

    {% block content %}{% endblock %}

    {% block navigate %}{% endblock %}

</body>
</html>

IS_ontology/templates/clf.html
{% extends "main.html" %}        

{% block content %}
{% if request.user.is_authenticated %}
<h1>Классификатор статей</h1>
        <div class="container">
            <form method="post" class="form center">
                {% csrf_token %}
                <textarea class="request_url" name="request_url" placeholder="Cсылка на статью"></textarea>
                <input type="submit" name="classify" value="Отправить">
            </form>
            <div class="type_info center">
                Тип статьи: {{ request_type }}
            </div>
            {% if show %}
            <h1>Добавить статью в базу</h1>
            <form method="post" class="form center">
                {% csrf_token %}
                <textarea class="request_des" name="request_description" placeholder="Описание статьи"></textarea>
                <input type="submit" name="add_to_base" value="Добавить">
            </form>
            <div class="type_info center">
                {% if show_verdict %}
                <p>{{ verdict }}, {{ description }}</p>
                {% endif %}
            </div>
            {% endif %}
        </div>
{% endif %}

{% endblock %}

IS_ontology/templates/eng_rate.html
{% extends "main.html" %}
{% block content %}
	<h1>Рейтинг инженеров-онтологов</h1>

	<table cellpadding=10 border=1>
		<tr>
			<th>Инженер</th>
			<th>Количество сущностей</th>
			<th>Количество триплетов</th>
			<th>Рейтинг</th>
		</tr>
		{% for user, count_ents, count_triples, rating in eng_rate %}
		<tr>
			<td>{{ user }}</td>
			<td>{{ count_ents }}</td>
			<td>{{ count_triples }}</td>
			<td>{{ rating }}</td>
		</tr>
		{% endfor %}
	</table>


{% endblock %}

IS_ontology/templates/fstek.html
{% extends "main.html" %}
{% block content %}
	<h1>Список приказов ФСТЭК</h1>

	<table cellpadding=10 border=1>
		<tr>
		<th>Номер</th><th>Содержание</th><th>Ссылка</th>
		</tr>
		<tr>
		<td>ФЗ-187</td>
		<td>О БЕЗОПАСНОСТИ КРИТИЧЕСКОЙ ИНФОРМАЦИОННОЙ ИНФРАСТРУКТУРЫ РОССИЙСКОЙ ФЕДЕРАЦИИ</td>
		<td>https://fstec.ru/tekhnicheskaya-zashchita-informatsii/obespechenie-bezopasnosti-kriticheskoj-informatsionnoj-infrastruktury/285-zakony/1610-federalnyj-zakon-ot-26-iyulya-2017-g-n-187-fz</td>
		</tr>
		<tr>
		<td>ФЗ-152</td>
		<td>О персональных данных</td>
		<td>https://rg.ru/2006/07/29/personaljnye-dannye-dok.html</td>
		</tr>
		<tr>
		<td>ФЗ-149</td>
		<td>Об информации, информационных технологиях и о защите информации</td>
		<td>/://rg.ru/2006/07/29/informacia-dok.html</td>
		</tr>
	</table>

{% endblock %}

IS_ontology/templates/fz.html
{% extends "main.html" %}
{% block content %}
	<h1>Список федеральных законов</h1>

	<table cellpadding=10 border=1>
		<tr>
		<th>Номер</th><th>Содержание</th><th>Ссылка</th>
		</tr>
		<tr>
		<td>ФЗ-187</td>
		<td>О БЕЗОПАСНОСТИ КРИТИЧЕСКОЙ ИНФОРМАЦИОННОЙ ИНФРАСТРУКТУРЫ РОССИЙСКОЙ ФЕДЕРАЦИИ</td>
		<td>https://fstec.ru/tekhnicheskaya-zashchita-informatsii/obespechenie-bezopasnosti-kriticheskoj-informatsionnoj-infrastruktury/285-zakony/1610-federalnyj-zakon-ot-26-iyulya-2017-g-n-187-fz</td>
		</tr>
		<tr>
		<td>ФЗ-152</td>
		<td>О персональных данных</td>
		<td>https://rg.ru/2006/07/29/personaljnye-dannye-dok.html</td>
		</tr>
		<tr>
		<td>ФЗ-149</td>
		<td>Об информации, информационных технологиях и о защите информации</td>
		<td>/://rg.ru/2006/07/29/informacia-dok.html</td>
		</tr>
	</table>

{% endblock %}

IS_ontology/templates/index.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>{% block title %}Главная{% endblock %}Доска объявлений</title>
	{% bootstrap_css %}
	<link rel="stylesheet" type="text/css" href="{% static '../static/css/main.css' %}">
	{% bootstrap_javascript jquery='slim' %}
    <script src="{% static "js/htmx.min.js" %}"></script>
	<style>
		#viz {
             width: 800px;
             height: 700px;
        }
	</style>
</head>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'  class="container-fluid">
	<header class="mb-4">
		<hl class="display-1 text-center"></hl>
	</header>

<div class="row">
	<ul class="col nav justify-content-end border">
		{% if request.user.is_authenticated %}
		Приветствуем, {{ request.user.username }}!
		{% endif %}



		<li class="nav-item">
			<a class="nav-link" href="{% url 'register' %}">Регистрация</a>
		</li>
	
		{% if request.user.is_authenticated %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'logout' %}">Bыxoд</a>
			</li>
		{% else %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'login' %}">Bxoд</a>
			</li>
		{% endif %}
	</ul>
</div>

<div class="row">
	<nav class="col-md-auto nav flex-column border">
		<a class="nav-link root" href="{% url 'Notes:main' %}">Главная</a>
		<span class="nav-link root font-weight-bold dropdown">Законодательство</span>
		<a class="nav-link root" href="{% url 'Notes:fz' %}">Федеральные законы</a>
		<a class="nav-link root" href="{% url 'Notes:pp' %}">Постановления правительства</a>
		<a class="nav-link root" href="{% url 'Notes:fstek' %}">Приказы ФСТЭК</a>
		{% if request.user.is_authenticated %}
		<span class="nav-link root font-weight-bold" href="#">Словарь</span>
		<a class="nav-link root" href="/next/terms">Термины</a>
		<a class="nav-link root" href="{% url 'Notes:triplets' %}">Триплеты</a>
		{% endif %}
		<span class="nav-link root font-weight-bold" href="#">Документы</span>
		<span class="nav-link root font-weight-bold" href="#">Отчеты</span>
		<a class="nav-link" href="{% url 'Notes:rep_2021_jul' %}">Отчет за июль 2021 года </a>
		<a class="nav-link" href="{% url 'Notes:rep_2021_aug' %}">Отчет за август 2021 года </a>

		{% if request.user.is_authenticated %}
			<span class="nav-link root font-weight-bold" href="#">Инструменты</span>
			<a class="nav-link" href="{% url 'Clf:clf' %}">Классификатор статей </a>
			<a class="nav-link" href="{% url 'Ie:ie' %}">Извлечение сущностей</a>
		    <a class="nav-link" href="{% url 'Notes:terms_to_vote' %}">Голосование за сущности</a>
			<a class="nav-link" href="{% url 'Ie:predicates' %}">Предикаты</a>
			<a class="nav-link" href="{% url 'Ie:add' %}">Построение триплетов</a>
			<a class="nav-link" href="{% url 'Notes:triples_to_vote' %}">Голосование за триплеты</a>
			<a class="nav-link" href="{% url 'Ie:graph' %}">Граф знаний</a>
		{% endif %}

		<span class="nav-link root font-weight-bold" href="#">Состав рабочей группы</span>
		<a class="nav-link root" href="{% url 'Notes:companies' %}">Компании-участники</a>
		<a class="nav-link root" href="{% url 'Notes:members' %}">Эксперты</a>
		<a class="nav-link root" href="{% url 'Notes:expert_rating' %}">Рейтинг экспертов</a>
		<a class="nav-link root" href="{% url 'Notes:engineer_rating' %}">Рейтинг инженеров</a>
	</nav>
<section class="col border py-2">
{% bootstrap_messages %}
{% block content %}
{% endblock %}
</section>
</div>
<footer class="mt-3">
<p class="text-right font-italic">&copy; ЦК КБ "Энерджинет", 2021 г.</p>
</footer>
</body>
</html>

IS_ontology/templates/main.html
{% extends 'index.html' %}

{% block content %}

<h1>Центр Компетенций «Кибербезопасность» НТИ Энерджинет</h1>

<p>
<b>Миссия ЦК ИБ:</b>
<br>
Создать платформу и обеспечить развитие рынка цифровых знаний по ИБ.
</p>

<p>
<b>Цели ЦК ИБ:</b>
<br>
Выработать единый понятийный аппарат в сфере информационной и кибербезопасности.
Сделать знания по ИБ оцифрованным и доступными для всех.
Реализовывать проекты на базе открытой цифровой базы знаний по ИБ
</p>

<p>
<b>Возможности применения открытой цифровой базы знаний ИБ:</b>
<br>
Консолидация, корректировка и развитие государственной нормативной базы.
Интерактивное взаимодействие государственных органов, образования, экспертов, бизнеса и т.д.
Создание системы знаний и процессов ИБ в государстве, у предприятий и разработчиков продуктов.
образовательных программ и научных работ в образовательной среде.
Предоставление цифровой платформы и знаний для минимизации рисков и негативных последствий от киберинцидентов в ТЭК.
</p>



{% endblock %}

IS_ontology/templates/members.html
{% extends 'index.html' %}
{% load static %}

{% block content %}

<h1>Команда разработчиков сервиса</h1>

<br>
<table cellpadding=10 border=1>
	<tr>
		<td>Савин Михаил</td><td>Кит-Р</td><td>msavin@ussc.ru</td>
	</tr>
	<tr>
		<td>Чернышов Юрий</td><td>Сайберлимфа</td><td>ychernyshov@udv.group</td>
	</tr>
	<tr>
		<td>Бредихин Борис</td><td>Сайберлимфа</td><td>bbredikhin@udv.group</td>
	</tr>
</table>

{% endblock %}

IS_ontology/templates/page_InputNote.html
{% extends "base.html" %}
{% block title %} Создание нового триплета {% endblock %}

{% block info %}{% endblock %}

{% block content %}
	{% if saved %}
	  <h1>Спасибо!</h1>
	  <p>Триплет "{{ note.title }}" был успешно сохранен "{{ note.publish }}".</p>
	{% else %}
	  <h1>Создание нового триплета</h1>
	  <p>Пожалуйста, задайте значения нового триплета здесь.</p>
	  <form method="post">
	    {% csrf_token %}
	    {{ form.as_p }}
	    <input type="submit" value="Сохранить триплет">
	  </form>
	{% endif %}
{% endblock %}

{% block navigate %}
	{% if request.user.is_authenticated %}
                <p>Перейти к вашему списку триплетов <a href="{% url "Notes:notes_list" %}">здесь</a>.</p>
                <p><a href="{% url "logout" %}">Выход</a>.</p>
	{% else %}    
                <p><a href="{% url "login" %}">Вход</a>. </p>
	{% endif %}
{% endblock %}

IS_ontology/templates/predicates.html
{% extends "main.html" %}

{% block content %}

{% if request.user.is_authenticated %}
<h1>Найти описание предиката</h1>
        <form method="POST">
            {% csrf_token %}
            <textarea class="request_url" name="pred" placeholder="Введите наименование предиката"></textarea>
            <input type="submit" name="find_pred" value="Найти предикат">
        </form>
        <p>{{ pred_descriptions }}</p>

<h1>Добавить предикат</h1>
        <p>Не добавляйте новый предикат, пока не убедитесь, что его нет в базе</p>
        <form method="POST">
            {% csrf_token %}
            <textarea class="request_url" name="pred" placeholder="Предикат"></textarea>
            <textarea class="request_url" name="pred_description" placeholder="Описание предиката"></textarea>
            <input type="submit" name="add_pred" value="Добавить предикат">
        </form>
        <p>{{ verdict_pred }}</p>
{% endif %}

{% endblock %}

IS_ontology/templates/register.html
{% extends "base.html" %}
{% block title %}Create an account{% endblock %}
{% block content %}
<h1>Create an account</h1>
<p>Please, sign up using the following form:</p>
<form method="post">
{% csrf_token %}
{{ user_form.as_p }}
<p><input type="submit" value="Create my account"></p>
</form>
{% endblock %}

IS_ontology/templates/register_done.html
{% extends "base.html" %}
{% block title %}Welcome{% endblock %}
{% block content %}
<h1>Welcome {{ new_user.first_name }}!</h1>
<p>Your account has been successfully created.
Now you can <a href="{% url "login" %}">log in</a>.</p>
{% endblock %}

IS_ontology/templates/terms_table.html
<table cellpadding=10 border=1>
    <tr>
        <th>Термин<br><button>По возрастанию</button><br><button>По убыванию</button></th>
        <th>Документ<br><button>По возрастанию</button><br><button>По убыванию</button></th>
        <th>Эксперт<br><button>По возрастанию</button><br><button>По убыванию</button></th>
        <th>Дата добавления<br><button>По возрастанию</button><br><button>По убыванию</button></th>
    </tr>
    {% for t in terms %}
    <tr>
        <td>{{ t.term}}</td>
        <td><a href="{{ t.doc.url }}">{{ t.doc.desc }}</a></td>
        <td>{{ t.expert }}</td>
        <td>{{ t.date|date }}</td>
    </tr>
    {% endfor %}
</table>

IS_ontology/templates/triplet_table.html
<table cellpadding=10 border=1>
    <tr>
        <th>Субъект</th>
        <th>Объект</th>
        <th>Предикат</th>
        <th>Документ</th>
        <th>Эксперт</th>
        <th>Дата добавления</th>
    </tr>
    {% for t in triples %}
    <tr>
        <td>{{ t.sub }}</td>
        <td>{{ t.obj }}</td>
        <td>{{ t.pred }}</td>
        <td><a href="{{ t.source.url }}">{{ t.source.desc }}</a></td>
        <td>{{ t.expert }}</td>
        <td>{{ t.date|date }}</td>
    </tr>
    {% endfor %}
</table>